CREATE DATABASE ECOM; -- creating database
USE ECOM;	-- using the database

-- creating tables
-- customers

CREATE TABLE CUSTOMERS(
CUST_ID VARCHAR(255),
FIRST_NAME VARCHAR(250),
LAST_NAME VARCHAR(255),
EMAIL VARCHAR(250),
GENDER ENUM("Male","Female","Others"),
PHONE VARCHAR(10),
ANNUAL_INCOME DECIMAL(10,2));

SELECT * 
FROM CUSTOMERS;

DESCRIBE CUSTOMERS;

-- PRODUCT TABLE

CREATE TABLE PRODUCTS(
PROD_ID INT PRIMARY KEY,
PROD_NAME VARCHAR(255) UNIQUE,
UNIT_PRICE DECIMAL(10,2),
CATEGORY VARCHAR(200));

ALTER TABLE CUSTOMERS
MODIFY COLUMN  CUST_ID VARCHAR(255) PRIMARY KEY;

DESCRIBE CUSTOMERS;

-- SALES TABLE

CREATE TABLE SALES(
QUANTITY INT,
SALES DECIMAL(9,2),
CUST_ID VARCHAR(200),
PROD_ID INT,
DISCOUNT DECIMAL(3,2),
LOCATION CHAR(50),
ORDER_DATE DATE,
DELIVERY_DATE DATE,
PROFIT DECIMAL(9,2));

ALTER TABLE SALES
ADD CONSTRAINT FOREIGN KEY (CUST_ID) REFERENCES CUSTOMERS(CUST_ID),
ADD CONSTRAINT FOREIGN KEY (PROD_ID) REFERENCES PRODUCTS(PROD_ID);

DESCRIBE SALES;

-- INSERTING DATA ON CUSTOMERS

INSERT INTO CUSTOMERS(CUST_ID,FIRST_NAME,LAST_NAME,EMAIL,GENDER,PHONE,ANNUAL_INCOME)
VALUES
("CUST-101","Veena","Kutty","veena.kutty@gmail.com","Female","1234567890",55000);

INSERT INTO CUSTOMERS VALUES
("CUST-102","Alex",NULL,"alex@gmail.com","Male","0987654321",50000),
("CUST-103","Alice","George",NULL,"Female","9088989765",75000),
("CUST-104","Ram","Patel","ram.patel@gmail.com","Male",NULL,60000),
("CUST-105","Hitesh","Hirwani","hitesh.hirwani@gmail.com","Male","656563473",65000);

SELECT *
FROM CUSTOMERS;

SELECT FIRST_NAME,GENDER
FROM CUSTOMERS;

-- Modify Tables

ALTER TABLE SALES
ADD COLUMN SALE_ID INT AUTO_INCREMENT PRIMARY KEY;

ALTER TABLE CUSTOMERS
MODIFY COLUMN FIRST_NAME VARCHAR(255) NOT NULL;

ALTER TABLE PRODUCTS
MODIFY COLUMN PROD_NAME VARCHAR(255) NOT NULL,
MODIFY COLUMN UNIT_PRICE DECIMAL(10,2) NOT NULL;

ALTER TABLE PRODUCTS
ADD CONSTRAINT CHECK (UNIT_PRICE >0);

ALTER TABLE SALES
ADD CONSTRAINT CHECK (QUANTITY >0);

ALTER TABLE SALES
ADD CONSTRAINT CHECK (DISCOUNT BETWEEN 0 AND 1);

CREATE TABLE PAYMENTS(
PAYMENT_ID INT AUTO_INCREMENT PRIMARY KEY,
ORDER_ID INT NOT NULL,
PAYMENT_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
PAYMENT_METHOD ENUM ('UPI','CARD','NET BANKING','COD'),
PAYMENT_AMOUNT DECIMAL(10,2) NOT NULL,
PAYMENT_STATUS ENUM ('PENDING','COMPLETED','FAILED','REFUNDED') DEFAULT 'PENDING');

CREATE TABLE ORDERS(
ORDER_ID INT AUTO_INCREMENT PRIMARY KEY,
CUST_ID VARCHAR (255),
ORDER_STATUS ENUM ('PENDING','SHIPPING','DELIVERED','CANCELLED','CONFIRMED','ON THE WAY') DEFAULT 'PENDING',
SHIPPING_ADDRESS VARCHAR(255),
FOREIGN KEY (CUST_ID) REFERENCES CUSTOMERS(CUST_ID));

ALTER TABLE PAYMENTS
ADD CONSTRAINT
FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID);

-- INSERT DATA

SET FOREIGN_KEY_CHECKS =1;

INSERT INTO PRODUCTS VALUES
(1001,"MEN'S T-SHIRT",400,"CLOTHING"),
(1002,"SHOES",1500,"FOOT -WEAR"),
(1003,"APPLE WATCH",68000,"ELECTRONIC"),
(1004,"TABLE",15000,"FURNITURE"),
(1005,"HEELS",400,"FOOT-WEAR"),
(1006,"SAMSUNG S26 ULTRA",135000,"ELECTRONIC");

INSERT INTO ORDERS VALUE
(1101,'CUST-103','PENDING','MUMBAI');

INSERT INTO ORDERS(CUST_ID,ORDER_STATUS,SHIPPING_ADDRESS)VALUES
('CUST-104','DELIVERED','PUNE'),
('CUST-101','ON THE WAY','DELHI'),
('CUST-102','CONFIRMED','NAGPUR'),
('CUST-101','CANCELLED','NASHIK'),
('CUST-105','SHIPPED','NASHIK'),
('CUST-101','DELIVERED','HARYANA'),
('CUST-104','CANCELLED','PUNE'),
('CUST-102','ON THE WAY','NAGPUR'),
('CUST-102','SHIPPED','MUMBAI');

SELECT * FROM PRODUCTS;










